title: quaranthoughts
description: >-
  <p>
    Documenting my thoughts and experiences during the Covid19 pandemic. <br />
  </p>
  <p>
  Inspired by this article: <a href="https://news.virginia.edu/content/write-it-down-historian-suggests-keeping-record-life-during-pandemic" target="_blank">Write it down.</a>
  </p>
author: Jadurani Davalos
twitter_username: jadurani
github_username:  jadurani

theme: jekyll-theme-minimal

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"